### PR TITLE
Update golang, postgres and postgis versions

### PR DESCRIPTION
**Pull request by philippks**
Credits go to mccaffers. I just used the newest versions: https://github.com/OSMNames/OSMNames/pull/209

### CODE REVIEW

**Comment by dagnelies** [comment]
Hmmm... I'm running into the following error when calling `docker-compose run --rm osmnames`:

```
 => ERROR [ 2/11] RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' >> /etc/apt/sources.list &&     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -         1.3s
------
 > [ 2/11] RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' >> /etc/apt/sources.list &&     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -:
#0 0.771 Warning: apt-key output should not be parsed (stdout is not a terminal)
#0 0.892 gpg: no valid OpenPGP data found.
------
failed to solve: executor failed running [/bin/sh -c echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' >> /etc/apt/sources.list &&     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -]: exit code: 2
```

**Comment by philippks** [comment]
> Hmmm... I'm running into the following error when calling `docker-compose run --rm osmnames`:
> 
> ```
>  => ERROR [ 2/11] RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' >> /etc/apt/sources.list &&     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -         1.3s
> ------
>  > [ 2/11] RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' >> /etc/apt/sources.list &&     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -:
> #0 0.771 Warning: apt-key output should not be parsed (stdout is not a terminal)
> #0 0.892 gpg: no valid OpenPGP data found.
> ------
> failed to solve: executor failed running [/bin/sh -c echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' >> /etc/apt/sources.list &&     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -]: exit code: 2
> ```
> 
> ...or is that due to some caching issue?

the happens happens when you rebuild with `docker-compose build` ?

**Comment by dagnelies** [comment]
Nope. The issue remains. I don't exactly know what these 2 lines do, but commenting them out makes the Dockerfile build.

```
#RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' >> /etc/apt/sources.list && \
#    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
```

I noticed also a slight issue. The command `CMD ["./run.py"]` ran into a "path not found problem" on my side, perhaps because I'm on windows, and I had to replace it with `CMD python3 run.py` to work.

Sadly, this leads to another error following up:

```
skip database init, since it is already initialized
2023-02-03 12:30:47,432 - INFO - run wget --no-clobber --directory-prefix /osmnames/data/import/ http://www.nominatim.org/data/wikipedia_article.sql.bin
File ‘/osmnames/data/import/wikipedia_article.sql.bin’ already there; not retrieving.

2023-02-03 12:30:47,440 - INFO - finished
2023-02-03 12:30:47,440 - INFO - run wget --no-clobber --directory-prefix /osmnames/data/import/ https://www.nominatim.org/data/wikipedia_redirect.sql.bin
File ‘/osmnames/data/import/wikipedia_redirect.sql.bin’ already there; not retrieving.

2023-02-03 12:30:47,447 - INFO - finished
Traceback (most recent call last):
  File "run.py", line 30, in <module>
    run()
  File "run.py", line 22, in run
    import_wikipedia()
  File "/osmnames/osmnames/import_wikipedia/import_wikipedia.py", line 22, in import_wikipedia
    restore_wikipedia_dumps()
  File "/osmnames/osmnames/import_wikipedia/import_wikipedia.py", line 36, in restore_wikipedia_dumps
    _create_temporary_user_for_dump()
  File "/osmnames/osmnames/import_wikipedia/import_wikipedia.py", line 56, in _create_temporary_user_for_dump
    exec_sql(query, user="postgres")
  File "/osmnames/osmnames/database/functions.py", line 29, in exec_sql
    cursor.execute(sql)
psycopg2.ProgrammingError: role "brian" already exists
```

**Comment by dagnelies** [comment]
wait a sec... I think I was in the wrong terminal ...I mixed up some paths...

**Comment by philippks** [comment]
> Nope. The issue remains. I don't exactly know what these 2 lines do, but commenting them out makes the Dockerfile build.

@dagnelies even though the commands work for me, I removed them, since the same postgres-client version was installed in both cases.

could you please try to build without cache `docker-compose --no-cache build`

and the later error looks like there is some dangling wikipedia data... you could remove the volumes with `docker-compose down -v`, but this will remove all data! Importing the wikipedia dump will take some time...

alternatively you can skip wikipedia by settings `SKIP_WIKIPEDIA=True` in the `.env` file.

**Comment by dagnelies** [comment]
Looks like it works 👍  ...I'm going for lunch right now and confirm it later

**Comment by dagnelies** [comment]
It works. Perfect. Nice job 🎉

**Comment by philippks** [comment]
> It works. Perfect. Nice job 🎉

great, thanks for checking 🙏

**Pull request merged**
